name: Build AuroraChat Windows

on:
  push:
    branches: [ "**" ]
    paths:
      - 'Cargo.toml'
      - 'source/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ "**" ]
    paths:
      - 'Cargo.toml'
      - 'source/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container: rust:1.97.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Add windows target
        run: rustup target add x86_64-pc-windows-msvc
      
      - name: Build Project
        run: cargo build --target x86_64-pc-windows-gnu

      - name: Upload windows build
        uses: actions/upload-artifact@v7
        with:
          name: AuroraChat Windows Automatic Build (could be unfinished!)
          path: ./aurorachat-windows.exe
      