name: Build AuroraChat Windows

on:
  push:
    branches: [ "**" ]
    paths:
      - 'Cargo.toml'
      - 'source/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ "**" ]
    paths:
      - 'Cargo.toml'
      - 'source/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container: rust:1.97.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - run: apt-get update && apt-get install -y gcc-mingw-w64-x86-64
      - run: rustup target add x86_64-pc-windows-gnu
      - run: cargo build --target x86_64-pc-windows-gnu -vv 2>&1 | tee build.log | grep -B5 "link.exe" || true
      - name: Upload windows build
        uses: actions/upload-artifact@v7
        with:
          name: AuroraChat Windows Automatic Build (could be unfinished!)
          path: ./aurorachat-windows.exe
      